apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: tap-dev
  name: tanzu-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web 
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-app
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: ssh://git@github.com/ezYakaEagle442/tanzu-petclinic
      ref:
        branch: main
    subPath: spring-petclinic-config-server
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11.*"
