apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  namespace: tap-dev
  name: tanzu-petclinic-config
  labels:
    apps.tanzu.vmware.com/workload-type: web 
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-app
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/ezYakaEagle442/tanzu-petclinic # ssh://git@github.com/ezYakaEagle442/tanzu-petclinic ==> TAP on AKS need GH SSH Keys to access the repo in that case
      ref:
        branch: main
    subPath: spring-petclinic-config-server
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: "default"
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11.*"
